### ISSUE TITLE
Just Install fails

### ISSUE THREAD

**Issue by yungryce** [ava-world/TUTORIALS#1]
Running just Install following the tutorial returns the following error on gitpod

```
root /home/gitpod/first-xcounter (main) $ just install
echo "Installing dependencies"
Installing dependencies
npm install

up to date, audited 643 packages in 1s

100 packages are looking for funding
  run `npm fund` for details

1 low severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
forge install --shallow
sh: 1: forge: not found
error: Recipe `install` failed on line 5 with exit code 127
```

**Comment by ava-world** [comment]
Thanks for the comments

for some reasons the node package needs to be reinstalled... probably has to do with the version in my tutorial it was a quick tutorial so not much detailed

What you need to do is to reinstall all dependencies again...note that you won't be needing the first 2 steps in the tutorial as you are using gitpod
